[package]
name = "tokio-vsock"
version = "0.1.1"
authors = ["fsyncd"]
description = "Asynchronous Virtio socket support for Rust"
repository = "https://github.com/fsyncd/tokio-vsock"
license = "Apache-2.0"
edition = "2018"
exclude = ["test_fixture"]

[dependencies]
bytes = "0.4.12"
futures = "0.3.5"
iovec = "0.1.4"
libc = "0.2.71"
mio = "0.6.20"
nix = "0.17.0"
vsock = "0.2.0"
tokio = { version = "0.2", features = ["io-driver", "stream", "macros", "rt-threaded", ] }

[dev-dependencies]
hyper = "0.12.35"
sha2 = "0.9.0"
rand = "0.7.3"
