[package]
name = "tokio-vsock"
version = "0.2.2"
authors = ["fsyncd"]
description = "Asynchronous Virtio socket support for Rust"
repository = "https://github.com/fsyncd/tokio-vsock"
license = "Apache-2.0"
edition = "2018"
exclude = ["test_fixture"]

[dependencies]
futures      = "0.3"
iovec        = "0.1"
libc         = "0.2"
mio          = "0.6"
nix          = "0.17"
vsock        = "0.2"
tokio        = { version = "1.1", features = ["net"] }
tokio-stream = "0.1"

[dev-dependencies]
sha2 = "0.9"
rand = "0.8"
tokio = { version = "1.1", features = ["macros", "rt", "io-util", "net"] }
